- name: Run PowerShell script from a file
  hosts: windows
  become_method: runas
  vars:
    - script: tcp-server.ps1
    - windows_directory: "C:\\temp-scripts"
    - windows_scrip_path: "{{windows_directory}}\\{{script}}"


  tasks:
    - name: create folder in Windows
      win_file:
        path: "{{windows_directory}}"
        state: directory

    - name: Copy PowerShell script to remote Windows machine
      win_copy:
        src: "./{{script}}"
        dest: "{{ windows_scrip_path }}"
        force: yes

    - name: Execute PowerShell script from file
      win_shell: "{{windows_scrip_path}}"
      become: yes
      become_user: Administrator
      async: 45
      poll: 0