- name: Run PowerShell script from a file
  hosts: windows
  become_method: runas
  vars:
    - script: tcp-server.ps1
    - windows_scrip_path: "C:\\Temp\\{{script}}"


  tasks:
    - name: Copy PowerShell script to remote Windows machine
      win_copy:
        src: "./{{script}}"
        dest: "{{ windows_scrip_path }}"
        force: yes

    - name: Execute PowerShell script from file
      win_shell: "{{windows_scrip_path}}"
      become: yes
      become_user: Administrator
      async: 45
      poll: 0